### PR TITLE
add trogworld page

### PR DESCRIPTION
**Pull request by soyuka**

### CODE REVIEW

**Review by GenesisFR — CHANGES_REQUESTED** [review]
Add "DS mods" between parenthesis, place it one line above as the links are sorted in alphabetical order and add yourself in the credits.

**Comment by soyuka** [comment]
Done. 

I'm playing this game on linux via wine, could I contribute on a HowTo wine installation?

**Comment by GenesisFR** [comment]
Sure, go ahead in another pull request, though keep in mind someone has already made a similar installation guide for DS2 https://github.com/GenesisFR/DS2TroubleshootingGuide/pull/1. I added the export to REG feature because of it but I've never heard from him since so I have no clue if it even works properly on Linux, could you test that out if you have time?

Also, I'll end up replicating this pull request instead of merging it as I have a strict nomenclature regarding commit syntax (you can check my past commits for examples) I learned at my first job:

\+ = addition
\- = modification
\* = fix

Thanks for your contribution. How would you like to be credited?

**Comment by soyuka** [comment]
You could use the `squash` (instead of merge) button and change the commit yourself 

The RegEdit thing is to make the system believe an older version of the game is installed. A similar thing helps to install dungeon siege editor on a steam verison of the game: https://steamcommunity.com/app/39190/discussions/0/882959527674476138/

**Review by GenesisFR — APPROVED** [review]

**Pull request merged**
